version: '3'

services:
  db:
    image: postgres
    volumes:
      - ./postgres-data:/var/lib/postgres

  web:
    build: ./django
    # Development command
    command: python3 manage.py runserver 0.0.0.0:8000
    environment:
      - DATABASE_NAME=postgres
      - DATABASE_USER=postgres
      - DATABASE_PORT=5432
      - DATABASE_HOST=db
    volumes:
      - ./django:/code
    ports:
      - "8000:8000"
    depends_on:
      - db